@inline function calculate_differential(
    x0::T, x1::T, x2::T, x3::T, v0::T, v1::T, v2::T, v3::T,
    metric::KerrMetric{T}) where {T}

    a = metric.a
    M = metric.M
    #block for macro application...
    @fastmath @inbounds begin

        #code generated by FastDifferentation.jl - need to find a way to automate this for arbitrary metrics.
        var"##248" = x1 * x1
        var"##249" = x2 * x2
        var"##247" = var"##248" + var"##249"
        var"##250" = x3 * x3
        var"##246" = var"##247" + var"##250"
        var"##251" = a * a
        var"##245" = var"##246" - var"##251"
        var"##254" = var"##245" ^ 2
        var"##256" = 4.0f0var"##251"
        var"##255" = var"##256" * var"##250"
        var"##253" = var"##254" + var"##255"
        var"##252" = sqrt(var"##253")
        var"##244" = var"##245" + var"##252"
        var"##243" = var"##244" * M
        var"##258" = 0.5f0var"##244"
        var"##257" = sqrt(var"##258")
        var"##242" = var"##243" * var"##257"
        var"##261" = var"##244" * var"##244"
        var"##260" = 0.25f0var"##261"
        var"##262" = var"##251" * var"##250"
        var"##259" = var"##260" + var"##262"
        var"##241" = var"##242" / var"##259"
        var"##240" = -1 - var"##241"
        var"##239" = var"##240" * v0
        var"##267" = var"##257" * x1
        var"##268" = a * x2
        var"##266" = var"##267" + var"##268"
        var"##269" = var"##258" + var"##251"
        var"##265" = var"##266" / var"##269"
        var"##264" = var"##241" * var"##265"
        var"##263" = var"##264" * v1
        var"##238" = var"##239" + var"##263"
        var"##274" = var"##257" * x2
        var"##275" = a * x1
        var"##273" = var"##274" - var"##275"
        var"##272" = var"##273" / var"##269"
        var"##271" = var"##241" * var"##272"
        var"##270" = var"##271" * v2
        var"##237" = var"##238" + var"##270"
        var"##278" = x3 / var"##257"
        var"##277" = var"##241" * var"##278"
        var"##276" = var"##277" * v3
        var"##236" = var"##237" + var"##276"
        dx0 = var"##236"
        var"##282" = var"##264" * v0
        var"##285" = var"##264" * var"##265"
        var"##284" = 1 - var"##285"
        var"##283" = var"##284" * v1
        var"##281" = var"##282" + var"##283"
        var"##288" = -var"##272"
        var"##287" = var"##288" * var"##264"
        var"##286" = var"##287" * v2
        var"##280" = var"##281" + var"##286"
        var"##291" = -var"##278"
        var"##290" = var"##291" * var"##264"
        var"##289" = var"##290" * v3
        var"##279" = var"##280" + var"##289"
        dx1 = var"##279"
        var"##295" = var"##271" * v0
        var"##296" = var"##287" * v1
        var"##294" = var"##295" + var"##296"
        var"##299" = var"##271" * var"##272"
        var"##298" = 1 - var"##299"
        var"##297" = var"##298" * v2
        var"##293" = var"##294" + var"##297"
        var"##302" = -var"##271"
        var"##301" = var"##302" * var"##278"
        var"##300" = var"##301" * v3
        var"##292" = var"##293" + var"##300"
        dx2 = var"##292"
        var"##306" = var"##277" * v0
        var"##307" = var"##290" * v1
        var"##305" = var"##306" + var"##307"
        var"##308" = var"##301" * v2
        var"##304" = var"##305" + var"##308"
        var"##311" = var"##277" * var"##278"
        var"##310" = 1 - var"##311"
        var"##309" = var"##310" * v3
        var"##303" = var"##304" + var"##309"
        dx3 = var"##303"
        dv0 = 0
        var"##325" = 1 / var"##269"
        var"##324" = var"##325" * x2
        var"##327" = 2var"##257"
        var"##326" = 1 / var"##327"
        var"##323" = var"##324" * var"##326"
        var"##329" = var"##272" / var"##269"
        var"##328" = -var"##329"
        var"##322" = var"##323" + var"##328"
        var"##332" = -var"##264"
        var"##334" = v1 * v2
        var"##335" = v2 * v1
        var"##333" = var"##334" + var"##335"
        var"##331" = var"##332" * var"##333"
        var"##337" = var"##302" * v2
        var"##336" = var"##337" * v2
        var"##330" = var"##331" + var"##336"
        var"##321" = var"##322" * var"##330"
        var"##339" = 3var"##326"
        var"##343" = var"##278" / var"##257"
        var"##342" = -var"##343"
        var"##341" = 2var"##342"
        var"##349" = v1 * v3
        var"##350" = v3 * v1
        var"##348" = var"##349" + var"##350"
        var"##347" = var"##348" * var"##332"
        var"##353" = v2 * v3
        var"##354" = v3 * v2
        var"##352" = var"##353" + var"##354"
        var"##351" = var"##352" * var"##302"
        var"##346" = var"##347" + var"##351"
        var"##357" = -(v3)
        var"##356" = var"##357" * var"##277"
        var"##355" = v3 * var"##356"
        var"##345" = var"##346" + var"##355"
        var"##362" = var"##291" * v3
        var"##361" = v0 + var"##362"
        var"##360" = var"##361" * v3
        var"##363" = v3 * v0
        var"##359" = var"##360" + var"##363"
        var"##358" = var"##359" * var"##241"
        var"##344" = var"##345" + var"##358"
        var"##340" = var"##341" * var"##344"
        var"##338" = var"##339" * var"##340"
        var"##320" = var"##321" + var"##338"
        var"##319" = 2.0f0var"##320"
        var"##368" = 1 / var"##259"
        var"##370" = var"##257" * M
        var"##372" = var"##243" * var"##326"
        var"##371" = 0.5f0var"##372"
        var"##369" = var"##370" + var"##371"
        var"##367" = var"##368" * var"##369"
        var"##376" = var"##241" / var"##259"
        var"##375" = -var"##376"
        var"##374" = var"##244" * var"##375"
        var"##373" = 0.5f0var"##374"
        var"##366" = var"##367" + var"##373"
        var"##365" = 2var"##366"
        var"##382" = var"##291" * var"##348"
        var"##384" = var"##288" * var"##333"
        var"##385" = v0 * v1
        var"##383" = var"##384" + var"##385"
        var"##381" = var"##382" + var"##383"
        var"##380" = var"##265" * var"##381"
        var"##390" = var"##288" * v2
        var"##389" = v0 + var"##390"
        var"##388" = var"##389" * v2
        var"##391" = var"##291" * var"##352"
        var"##387" = var"##388" + var"##391"
        var"##386" = var"##272" * var"##387"
        var"##379" = var"##380" + var"##386"
        var"##393" = 2var"##278"
        var"##392" = var"##393" * var"##359"
        var"##378" = var"##379" + var"##392"
        var"##396" = var"##333" * var"##288"
        var"##395" = var"##396" * var"##265"
        var"##400" = v3 * var"##278"
        var"##403" = -(v0)
        var"##404" = v1 * var"##265"
        var"##402" = var"##403" + var"##404"
        var"##405" = v2 * var"##272"
        var"##401" = var"##402" + var"##405"
        var"##399" = var"##400" + var"##401"
        var"##398" = v0 * var"##399"
        var"##410" = -(v1)
        var"##409" = var"##410" * var"##265"
        var"##408" = v0 + var"##409"
        var"##407" = var"##408" * var"##265"
        var"##406" = v1 * var"##407"
        var"##397" = var"##398" + var"##406"
        var"##394" = var"##395" + var"##397"
        var"##377" = var"##378" + var"##394"
        var"##364" = var"##365" * var"##377"
        var"##318" = var"##319" + var"##364"
        var"##411" = 2 * x1
        var"##317" = var"##318" * var"##411"
        var"##419" = x1 * var"##326"
        var"##418" = x1 * var"##419"
        var"##417" = var"##257" + var"##418"
        var"##416" = var"##325" * var"##417"
        var"##422" = var"##265" / var"##269"
        var"##421" = -var"##422"
        var"##420" = x1 * var"##421"
        var"##415" = var"##416" + var"##420"
        var"##414" = var"##241" * var"##415"
        var"##424" = var"##265" * var"##366"
        var"##423" = var"##424" * var"##411"
        var"##413" = var"##414" + var"##423"
        var"##412" = var"##381" * var"##413"
        var"##316" = var"##317" + var"##412"
        var"##429" = -(a)
        var"##431" = x2 * var"##326"
        var"##430" = x1 * var"##431"
        var"##428" = var"##429" + var"##430"
        var"##427" = var"##325" * var"##428"
        var"##432" = x1 * var"##328"
        var"##426" = var"##427" + var"##432"
        var"##425" = var"##330" * var"##426"
        var"##315" = var"##316" + var"##425"
        var"##435" = var"##241" * var"##426"
        var"##437" = var"##272" * var"##366"
        var"##436" = var"##437" * var"##411"
        var"##434" = var"##435" + var"##436"
        var"##433" = var"##387" * var"##434"
        var"##314" = var"##315" + var"##433"
        var"##441" = v2 * var"##434"
        var"##444" = var"##403" * var"##366"
        var"##443" = var"##444" * var"##411"
        var"##445" = v1 * var"##413"
        var"##442" = var"##443" + var"##445"
        var"##440" = var"##441" + var"##442"
        var"##439" = v0 * var"##440"
        var"##448" = v1 * v1
        var"##447" = -var"##448"
        var"##450" = var"##264" * var"##415"
        var"##451" = var"##265" * var"##413"
        var"##449" = var"##450" + var"##451"
        var"##446" = var"##447" * var"##449"
        var"##438" = var"##439" + var"##446"
        var"##313" = var"##314" + var"##438"
        var"##312" = -0.5f0var"##313"
        dv1 = var"##312"
        var"##458" = 2 * x2
        var"##457" = var"##318" * var"##458"
        var"##465" = x2 * var"##431"
        var"##464" = var"##257" + var"##465"
        var"##463" = var"##325" * var"##464"
        var"##466" = var"##328" * x2
        var"##462" = var"##463" + var"##466"
        var"##461" = var"##241" * var"##462"
        var"##468" = var"##366" * var"##458"
        var"##467" = var"##272" * var"##468"
        var"##460" = var"##461" + var"##467"
        var"##459" = var"##387" * var"##460"
        var"##456" = var"##457" + var"##459"
        var"##469" = var"##330" * var"##462"
        var"##455" = var"##456" + var"##469"
        var"##476" = x2 * var"##419"
        var"##475" = a + var"##476"
        var"##474" = var"##325" * var"##475"
        var"##477" = var"##421" * x2
        var"##473" = var"##474" + var"##477"
        var"##472" = var"##241" * var"##473"
        var"##478" = var"##424" * var"##458"
        var"##471" = var"##472" + var"##478"
        var"##470" = var"##381" * var"##471"
        var"##454" = var"##455" + var"##470"
        var"##482" = v2 * var"##460"
        var"##484" = var"##403" * var"##468"
        var"##485" = v1 * var"##471"
        var"##483" = var"##484" + var"##485"
        var"##481" = var"##482" + var"##483"
        var"##480" = v0 * var"##481"
        var"##490" = var"##264" * var"##473"
        var"##491" = var"##265" * var"##471"
        var"##489" = var"##490" + var"##491"
        var"##488" = var"##410" * var"##489"
        var"##492" = v0 * var"##471"
        var"##487" = var"##488" + var"##492"
        var"##486" = v1 * var"##487"
        var"##479" = var"##480" + var"##486"
        var"##453" = var"##454" + var"##479"
        var"##452" = -0.5f0var"##453"
        dv2 = var"##452"
        var"##501" = 1 / var"##257"
        var"##505" = 0.5f0var"##326"
        var"##509" = 2var"##252"
        var"##508" = 1 / var"##509"
        var"##507" = var"##508" * var"##256"
        var"##506" = var"##507" + 1
        var"##504" = var"##505" * var"##506"
        var"##510" = 2 * x3
        var"##503" = var"##504" * var"##510"
        var"##502" = var"##342" * var"##503"
        var"##500" = var"##501" + var"##502"
        var"##499" = var"##241" * var"##500"
        var"##515" = var"##369" * var"##506"
        var"##514" = var"##368" * var"##515"
        var"##518" = var"##258" * var"##506"
        var"##517" = var"##251" + var"##518"
        var"##516" = var"##375" * var"##517"
        var"##513" = var"##514" + var"##516"
        var"##512" = var"##513" * var"##510"
        var"##511" = var"##278" * var"##512"
        var"##498" = var"##499" + var"##511"
        var"##497" = var"##359" * var"##498"
        var"##519" = var"##344" * var"##500"
        var"##496" = var"##497" + var"##519"
        var"##528" = 0.5f0var"##322"
        var"##527" = var"##528" * var"##506"
        var"##526" = var"##241" * var"##527"
        var"##529" = var"##272" * var"##513"
        var"##525" = var"##526" + var"##529"
        var"##524" = v2 * var"##525"
        var"##531" = var"##403" * var"##513"
        var"##535" = 0.5f0var"##241"
        var"##539" = var"##325" * x1
        var"##538" = var"##539" * var"##326"
        var"##537" = var"##538" + var"##421"
        var"##536" = var"##537" * var"##506"
        var"##534" = var"##535" * var"##536"
        var"##540" = var"##265" * var"##513"
        var"##533" = var"##534" + var"##540"
        var"##532" = v1 * var"##533"
        var"##530" = var"##531" + var"##532"
        var"##523" = var"##524" + var"##530"
        var"##522" = v0 * var"##523"
        var"##547" = 0.5f0var"##537"
        var"##546" = var"##547" * var"##506"
        var"##545" = var"##264" * var"##546"
        var"##548" = var"##265" * var"##533"
        var"##544" = var"##545" + var"##548"
        var"##543" = var"##410" * var"##544"
        var"##549" = v0 * var"##533"
        var"##542" = var"##543" + var"##549"
        var"##541" = v1 * var"##542"
        var"##521" = var"##522" + var"##541"
        var"##520" = var"##521" * var"##510"
        var"##495" = var"##496" + var"##520"
        var"##553" = var"##318" * var"##506"
        var"##554" = var"##381" * var"##533"
        var"##552" = var"##553" + var"##554"
        var"##555" = var"##387" * var"##525"
        var"##551" = var"##552" + var"##555"
        var"##550" = var"##551" * var"##510"
        var"##494" = var"##495" + var"##550"
        var"##493" = -0.5f0var"##494"
        dv3 = var"##493"

    end
    
    return dx0, dx1, dx2, dx3, dv0, dv1, dv2, dv3

end

@inline function calculate_differential(state::NTuple{N, T}, metric::KerrMetric{T}) where {N,T}
    x0, x1, x2, x3, v0, v1, v2, v3 = state
    dstate = calculate_differential(x0, x1, x2, x3, v0, v1, v2, v3, metric)
    return dstate
end

@inline function yield_r2(x0::T, x1::T, x2::T, x3::T, metric::KerrMetric{T}) where T

    a = metric.a
    M = metric.M
    @fastmath begin
        x1_2 = x1*x1
        x2_2 = x2*x2
        x3_2 = x3*x3
        R2 = x1_2 + x2_2 + x3_2
        a2 = a*a
        sub1 = R2 - a2
        r2 = T(0.5) * (sub1 + sqrt(sub1^2 + T(4) * a2 * x3_2))
    end

    return r2

end

@inline function RK4step(x0::T, x1::T, x2::T, x3::T, v0::T, v1::T, v2::T, v3::T, 
                         metric::KerrMetric{T}, dt::T) where T

                        #for some reason, the original, tuble-base logic allocated here.
    @fastmath begin 
        dx0_1, dx1_1, dx2_1, dx3_1, dv0_1, dv1_1, dv2_1, dv3_1 = 
            calculate_differential(x0, x1, x2, x3, v0, v1, v2, v3, metric)
        dt_half = dt * T(0.5)
        dx0_2, dx1_2, dx2_2, dx3_2, dv0_2, dv1_2, dv2_2, dv3_2 = 
            calculate_differential(
                x0 + dt_half * dx0_1,
                x1 + dt_half * dx1_1,
                x2 + dt_half * dx2_1,
                x3 + dt_half * dx3_1,
                v0 + dt_half * dv0_1,
                v1 + dt_half * dv1_1,
                v2 + dt_half * dv2_1,
                v3 + dt_half * dv3_1,
                metric
            )

        dx0_3, dx1_3, dx2_3, dx3_3, dv0_3, dv1_3, dv2_3, dv3_3 = 
            calculate_differential(
                x0 + dt_half * dx0_2,
                x1 + dt_half * dx1_2,
                x2 + dt_half * dx2_2,
                x3 + dt_half * dx3_2,
                v0 + dt_half * dv0_2,
                v1 + dt_half * dv1_2,
                v2 + dt_half * dv2_2,
                v3 + dt_half * dv3_2,
                metric
            )

        dx0_4, dx1_4, dx2_4, dx3_4, dv0_4, dv1_4, dv2_4, dv3_4 = 
            calculate_differential(
                x0 + dt * dx0_3,
                x1 + dt * dx1_3,
                x2 + dt * dx2_3,
                x3 + dt * dx3_3,
                v0 + dt * dv0_3,
                v1 + dt * dv1_3,
                v2 + dt * dv2_3,
                v3 + dt * dv3_3,
                metric
            )
        
        renorm_6 = 1 / T(6)
        renorm_3 = 1 / T(3)
        dx0 = renorm_6 * (dx0_1 + dx0_4) + renorm_3 * (dx0_2 + dx0_3)
        dx1 = renorm_6 * (dx1_1 + dx1_4) + renorm_3 * (dx1_2 + dx1_3)
        dx2 = renorm_6 * (dx2_1 + dx2_4) + renorm_3 * (dx2_2 + dx2_3)
        dx3 = renorm_6 * (dx3_1 + dx3_4) + renorm_3 * (dx3_2 + dx3_3)
        dv0 = renorm_6 * (dv0_1 + dv0_4) + renorm_3 * (dv0_2 + dv0_3)
        dv1 = renorm_6 * (dv1_1 + dv1_4) + renorm_3 * (dv1_2 + dv1_3)
        dv2 = renorm_6 * (dv2_1 + dv2_4) + renorm_3 * (dv2_2 + dv2_3)
        dv3 = renorm_6 * (dv3_1 + dv3_4) + renorm_3 * (dv3_2 + dv3_3)
    end
    
    return (dx0, dx1, dx2, dx3, dv0, dv1, dv2, dv3)
end