@inline function calculate_differential(
    x0::T, x1::T, x2::T, x3::T, v0::T, v1::T, v2::T, v3::T,
    metric::KerrMetric{T}) where {T}

    a = metric.a
    M = metric.M
    #block for macro application...
    @fastmath @inbounds begin

        #code generated by FastDifferentation.jl - need to find a way to automate this for arbitrary metrics.
        var"##248" = x1 * x1
        var"##249" = x2 * x2
        var"##247" = var"##248" + var"##249"
        var"##250" = x3 * x3
        var"##246" = var"##247" + var"##250"
        var"##251" = a * a
        var"##245" = var"##246" - var"##251"
        var"##254" = var"##245" ^ 2
        var"##256" = 4.0f0var"##251"
        var"##255" = var"##256" * var"##250"
        var"##253" = var"##254" + var"##255"
        var"##252" = sqrt(var"##253")
        var"##244" = var"##245" + var"##252"
        var"##243" = var"##244" * M
        var"##258" = 0.5f0var"##244"
        var"##257" = sqrt(var"##258")
        var"##242" = var"##243" * var"##257"
        var"##261" = var"##244" * var"##244"
        var"##260" = 0.25f0var"##261"
        var"##262" = var"##251" * var"##250"
        var"##259" = var"##260" + var"##262"
        var"##241" = var"##242" / var"##259"
        var"##240" = -1.0f0 - var"##241"
        var"##239" = var"##240" * v0
        var"##267" = var"##257" * x1
        var"##268" = a * x2
        var"##266" = var"##267" + var"##268"
        var"##269" = var"##258" + var"##251"
        var"##265" = var"##266" / var"##269"
        var"##264" = var"##241" * var"##265"
        var"##263" = var"##264" * v1
        var"##238" = var"##239" + var"##263"
        var"##274" = var"##257" * x2
        var"##275" = a * x1
        var"##273" = var"##274" - var"##275"
        var"##272" = var"##273" / var"##269"
        var"##271" = var"##241" * var"##272"
        var"##270" = var"##271" * v2
        var"##237" = var"##238" + var"##270"
        var"##278" = x3 / var"##257"
        var"##277" = var"##241" * var"##278"
        var"##276" = var"##277" * v3
        var"##236" = var"##237" + var"##276"
        dx0 = var"##236"
        var"##282" = var"##264" * v0
        var"##285" = var"##264" * var"##265"
        var"##284" = 1.0f0 - var"##285"
        var"##283" = var"##284" * v1
        var"##281" = var"##282" + var"##283"
        var"##289" = -var"##241"
        var"##288" = var"##289" * var"##265"
        var"##287" = var"##288" * var"##272"
        var"##286" = var"##287" * v2
        var"##280" = var"##281" + var"##286"
        var"##291" = var"##288" * var"##278"
        var"##290" = var"##291" * v3
        var"##279" = var"##280" + var"##290"
        dx1 = var"##279"
        var"##295" = var"##271" * v0
        var"##296" = var"##287" * v1
        var"##294" = var"##295" + var"##296"
        var"##299" = var"##271" * var"##272"
        var"##298" = 1.0f0 - var"##299"
        var"##297" = var"##298" * v2
        var"##293" = var"##294" + var"##297"
        var"##302" = var"##289" * var"##272"
        var"##301" = var"##302" * var"##278"
        var"##300" = var"##301" * v3
        var"##292" = var"##293" + var"##300"
        dx2 = var"##292"
        var"##306" = var"##277" * v0
        var"##307" = var"##291" * v1
        var"##305" = var"##306" + var"##307"
        var"##308" = var"##301" * v2
        var"##304" = var"##305" + var"##308"
        var"##311" = var"##277" * var"##278"
        var"##310" = 1.0f0 - var"##311"
        var"##309" = var"##310" * v3
        var"##303" = var"##304" + var"##309"
        dx3 = var"##303"
        dv0 = 0
        var"##321" = v1 * v2
        var"##322" = v2 * v1
        var"##320" = var"##321" + var"##322"
        var"##319" = var"##288" * var"##320"
        var"##325" = -var"##271"
        var"##324" = var"##325" * v2
        var"##323" = var"##324" * v2
        var"##318" = var"##319" + var"##323"
        var"##327" = var"##289" * var"##278"
        var"##329" = v2 * v3
        var"##330" = v3 * v2
        var"##328" = var"##329" + var"##330"
        var"##326" = var"##327" * var"##328"
        var"##317" = var"##318" + var"##326"
        var"##333" = 1 / var"##269"
        var"##335" = -(a)
        var"##339" = 2var"##257"
        var"##338" = 1 / var"##339"
        var"##337" = x2 * var"##338"
        var"##336" = x1 * var"##337"
        var"##334" = var"##335" + var"##336"
        var"##332" = var"##333" * var"##334"
        var"##342" = var"##272" / var"##269"
        var"##341" = -var"##342"
        var"##340" = x1 * var"##341"
        var"##331" = var"##332" + var"##340"
        var"##316" = var"##317" * var"##331"
        var"##347" = v1 * v1
        var"##346" = -var"##347"
        var"##345" = var"##346" * var"##264"
        var"##350" = var"##320" * var"##272"
        var"##353" = v1 * v3
        var"##354" = v3 * v1
        var"##352" = var"##353" + var"##354"
        var"##351" = var"##352" * var"##278"
        var"##349" = var"##350" + var"##351"
        var"##348" = var"##349" * var"##289"
        var"##344" = var"##345" + var"##348"
        var"##359" = x1 * var"##338"
        var"##358" = x1 * var"##359"
        var"##357" = var"##257" + var"##358"
        var"##356" = var"##333" * var"##357"
        var"##362" = var"##265" / var"##269"
        var"##361" = -var"##362"
        var"##360" = x1 * var"##361"
        var"##355" = var"##356" + var"##360"
        var"##343" = var"##344" * var"##355"
        var"##315" = var"##316" + var"##343"
        var"##371" = var"##333" * x1
        var"##370" = var"##371" * var"##338"
        var"##369" = var"##370" + var"##361"
        var"##368" = var"##369" * var"##344"
        var"##375" = var"##333" * x2
        var"##374" = var"##375" * var"##338"
        var"##373" = var"##374" + var"##341"
        var"##372" = var"##373" * var"##317"
        var"##367" = var"##368" + var"##372"
        var"##377" = 3var"##338"
        var"##381" = var"##278" / var"##257"
        var"##380" = -var"##381"
        var"##379" = 2var"##380"
        var"##385" = var"##352" * var"##288"
        var"##386" = var"##328" * var"##302"
        var"##384" = var"##385" + var"##386"
        var"##389" = -(v3)
        var"##388" = var"##389" * var"##277"
        var"##387" = v3 * var"##388"
        var"##383" = var"##384" + var"##387"
        var"##395" = -var"##278"
        var"##394" = var"##395" * v3
        var"##393" = v0 + var"##394"
        var"##392" = var"##393" * v3
        var"##396" = v3 * v0
        var"##391" = var"##392" + var"##396"
        var"##390" = var"##391" * var"##241"
        var"##382" = var"##383" + var"##390"
        var"##378" = var"##379" * var"##382"
        var"##376" = var"##377" * var"##378"
        var"##366" = var"##367" + var"##376"
        var"##365" = 2.0f0var"##366"
        var"##401" = 1 / var"##259"
        var"##403" = var"##257" * M
        var"##405" = var"##243" * var"##338"
        var"##404" = 0.5f0var"##405"
        var"##402" = var"##403" + var"##404"
        var"##400" = var"##401" * var"##402"
        var"##409" = var"##241" / var"##259"
        var"##408" = -var"##409"
        var"##407" = var"##244" * var"##408"
        var"##406" = 0.5f0var"##407"
        var"##399" = var"##400" + var"##406"
        var"##398" = 2var"##399"
        var"##414" = var"##349" * var"##265"
        var"##416" = var"##328" * var"##278"
        var"##415" = var"##416" * var"##272"
        var"##413" = var"##414" + var"##415"
        var"##412" = -var"##413"
        var"##418" = 2var"##278"
        var"##417" = var"##418" * var"##391"
        var"##411" = var"##412" + var"##417"
        var"##426" = -var"##272"
        var"##425" = var"##426" * v2
        var"##424" = v0 + var"##425"
        var"##423" = var"##424" * v2
        var"##427" = v2 * v0
        var"##422" = var"##423" + var"##427"
        var"##421" = var"##422" * var"##272"
        var"##435" = -var"##265"
        var"##434" = var"##435" * v1
        var"##433" = v0 + var"##434"
        var"##438" = -(v1)
        var"##437" = var"##438" * var"##265"
        var"##436" = v0 + var"##437"
        var"##432" = var"##433" + var"##436"
        var"##431" = var"##432" * v1
        var"##439" = v1 * v0
        var"##430" = var"##431" + var"##439"
        var"##429" = var"##430" * var"##265"
        var"##442" = v3 * var"##278"
        var"##445" = -(v0)
        var"##446" = v1 * var"##265"
        var"##444" = var"##445" + var"##446"
        var"##447" = v2 * var"##272"
        var"##443" = var"##444" + var"##447"
        var"##441" = var"##442" + var"##443"
        var"##440" = v0 * var"##441"
        var"##428" = var"##429" + var"##440"
        var"##420" = var"##421" + var"##428"
        var"##448" = var"##445" * v0
        var"##419" = var"##420" + var"##448"
        var"##410" = var"##411" + var"##419"
        var"##397" = var"##398" * var"##410"
        var"##364" = var"##365" + var"##397"
        var"##449" = 2 * x1
        var"##363" = var"##364" * var"##449"
        var"##314" = var"##315" + var"##363"
        var"##453" = var"##241" * var"##331"
        var"##455" = var"##272" * var"##399"
        var"##454" = var"##455" * var"##449"
        var"##452" = var"##453" + var"##454"
        var"##451" = var"##422" * var"##452"
        var"##458" = var"##241" * var"##355"
        var"##460" = var"##265" * var"##399"
        var"##459" = var"##460" * var"##449"
        var"##457" = var"##458" + var"##459"
        var"##456" = var"##430" * var"##457"
        var"##450" = var"##451" + var"##456"
        var"##313" = var"##314" + var"##450"
        var"##312" = -0.5f0var"##313"
        dv1 = var"##312"
        var"##466" = 2 * x2
        var"##465" = var"##364" * var"##466"
        var"##471" = x2 * var"##359"
        var"##470" = a + var"##471"
        var"##469" = var"##333" * var"##470"
        var"##472" = var"##361" * x2
        var"##468" = var"##469" + var"##472"
        var"##467" = var"##344" * var"##468"
        var"##464" = var"##465" + var"##467"
        var"##477" = x2 * var"##337"
        var"##476" = var"##257" + var"##477"
        var"##475" = var"##333" * var"##476"
        var"##478" = var"##341" * x2
        var"##474" = var"##475" + var"##478"
        var"##473" = var"##317" * var"##474"
        var"##463" = var"##464" + var"##473"
        var"##482" = var"##241" * var"##474"
        var"##484" = var"##399" * var"##466"
        var"##483" = var"##272" * var"##484"
        var"##481" = var"##482" + var"##483"
        var"##480" = var"##422" * var"##481"
        var"##487" = var"##241" * var"##468"
        var"##488" = var"##460" * var"##466"
        var"##486" = var"##487" + var"##488"
        var"##485" = var"##430" * var"##486"
        var"##479" = var"##480" + var"##485"
        var"##462" = var"##463" + var"##479"
        var"##461" = -0.5f0var"##462"
        dv2 = var"##461"
        var"##497" = 1 / var"##257"
        var"##501" = 0.5f0var"##338"
        var"##505" = 2var"##252"
        var"##504" = 1 / var"##505"
        var"##503" = var"##504" * var"##256"
        var"##502" = var"##503" + 1
        var"##500" = var"##501" * var"##502"
        var"##506" = 2 * x3
        var"##499" = var"##500" * var"##506"
        var"##498" = var"##380" * var"##499"
        var"##496" = var"##497" + var"##498"
        var"##495" = var"##241" * var"##496"
        var"##511" = var"##402" * var"##502"
        var"##510" = var"##401" * var"##511"
        var"##514" = var"##258" * var"##502"
        var"##513" = var"##251" + var"##514"
        var"##512" = var"##408" * var"##513"
        var"##509" = var"##510" + var"##512"
        var"##508" = var"##509" * var"##506"
        var"##507" = var"##278" * var"##508"
        var"##494" = var"##495" + var"##507"
        var"##493" = var"##391" * var"##494"
        var"##515" = var"##382" * var"##496"
        var"##492" = var"##493" + var"##515"
        var"##522" = 0.5f0var"##373"
        var"##521" = var"##522" * var"##502"
        var"##520" = var"##241" * var"##521"
        var"##523" = var"##272" * var"##509"
        var"##519" = var"##520" + var"##523"
        var"##518" = var"##519" * var"##506"
        var"##517" = var"##422" * var"##518"
        var"##529" = 0.5f0var"##241"
        var"##530" = var"##369" * var"##502"
        var"##528" = var"##529" * var"##530"
        var"##531" = var"##265" * var"##509"
        var"##527" = var"##528" + var"##531"
        var"##526" = var"##430" * var"##527"
        var"##534" = v0 * v0
        var"##533" = -var"##534"
        var"##532" = var"##533" * var"##509"
        var"##525" = var"##526" + var"##532"
        var"##524" = var"##525" * var"##506"
        var"##516" = var"##517" + var"##524"
        var"##491" = var"##492" + var"##516"
        var"##537" = var"##364" * var"##502"
        var"##538" = var"##410" * var"##509"
        var"##536" = var"##537" + var"##538"
        var"##535" = var"##536" * var"##506"
        var"##490" = var"##491" + var"##535"
        var"##489" = -0.5f0var"##490"
        dv3 = var"##489"

    end
    
    return dx0, dx1, dx2, dx3, dv0, dv1, dv2, dv3

end

@inline function calculate_differential(state::NTuple{N, T}, metric::KerrMetric{T}) where {N,T}
    x0, x1, x2, x3, v0, v1, v2, v3 = state
    dstate = calculate_differential(x0, x1, x2, x3, v0, v1, v2, v3, metric)
    return dstate
end

@inline function yield_r2(x0::T, x1::T, x2::T, x3::T, metric::KerrMetric{T}) where T

    a = metric.a
    M = metric.M
    @fastmath begin
        x1_2 = x1*x1
        x2_2 = x2*x2
        x3_2 = x3*x3
        R2 = x1_2 + x2_2 + x3_2
        a2 = a*a
        sub1 = R2 - a2
        r2 = T(0.5) * (sub1 + sqrt(sub1^2 + T(4) * a2 * x3_2))
    end

    return r2

end

@inline function RK4step(x0::T, x1::T, x2::T, x3::T, v0::T, v1::T, v2::T, v3::T, 
                         metric::KerrMetric{T}, dt::T) where T

                        #for some reason, the original, tuble-base logic allocated here.
    @fastmath begin 
        dx0_1, dx1_1, dx2_1, dx3_1, dv0_1, dv1_1, dv2_1, dv3_1 = 
            calculate_differential(x0, x1, x2, x3, v0, v1, v2, v3, metric)
        dt_half = dt * T(0.5)
        dx0_2, dx1_2, dx2_2, dx3_2, dv0_2, dv1_2, dv2_2, dv3_2 = 
            calculate_differential(
                x0 + dt_half * dx0_1,
                x1 + dt_half * dx1_1,
                x2 + dt_half * dx2_1,
                x3 + dt_half * dx3_1,
                v0 + dt_half * dv0_1,
                v1 + dt_half * dv1_1,
                v2 + dt_half * dv2_1,
                v3 + dt_half * dv3_1,
                metric
            )

        dx0_3, dx1_3, dx2_3, dx3_3, dv0_3, dv1_3, dv2_3, dv3_3 = 
            calculate_differential(
                x0 + dt_half * dx0_2,
                x1 + dt_half * dx1_2,
                x2 + dt_half * dx2_2,
                x3 + dt_half * dx3_2,
                v0 + dt_half * dv0_2,
                v1 + dt_half * dv1_2,
                v2 + dt_half * dv2_2,
                v3 + dt_half * dv3_2,
                metric
            )

        dx0_4, dx1_4, dx2_4, dx3_4, dv0_4, dv1_4, dv2_4, dv3_4 = 
            calculate_differential(
                x0 + dt * dx0_3,
                x1 + dt * dx1_3,
                x2 + dt * dx2_3,
                x3 + dt * dx3_3,
                v0 + dt * dv0_3,
                v1 + dt * dv1_3,
                v2 + dt * dv2_3,
                v3 + dt * dv3_3,
                metric
            )
        
        renorm_6 = 1 / T(6)
        renorm_3 = 1 / T(3)
        dx0 = renorm_6 * (dx0_1 + dx0_4) + renorm_3 * (dx0_2 + dx0_3)
        dx1 = renorm_6 * (dx1_1 + dx1_4) + renorm_3 * (dx1_2 + dx1_3)
        dx2 = renorm_6 * (dx2_1 + dx2_4) + renorm_3 * (dx2_2 + dx2_3)
        dx3 = renorm_6 * (dx3_1 + dx3_4) + renorm_3 * (dx3_2 + dx3_3)
        dv0 = renorm_6 * (dv0_1 + dv0_4) + renorm_3 * (dv0_2 + dv0_3)
        dv1 = renorm_6 * (dv1_1 + dv1_4) + renorm_3 * (dv1_2 + dv1_3)
        dv2 = renorm_6 * (dv2_1 + dv2_4) + renorm_3 * (dv2_2 + dv2_3)
        dv3 = renorm_6 * (dv3_1 + dv3_4) + renorm_3 * (dv3_2 + dv3_3)
    end
    
    return (dx0, dx1, dx2, dx3, dv0, dv1, dv2, dv3)
end