@inline function calculate_differential(
    x0::T, x1::T, x2::T, x3::T, v0::T, v1::T, v2::T, v3::T,
    metric::KerrMetric{T}) where {T}

    a = metric.a
    M = metric.M
    #block for macro application...
    @fastmath @inbounds begin

        #code generated by FastDifferentation.jl - need to find a way to automate this for arbitrary metrics.
        var"##248" = x1 * x1
        var"##249" = x2 * x2
        var"##247" = var"##248" + var"##249"
        var"##250" = x3 * x3
        var"##246" = var"##247" + var"##250"
        var"##251" = a * a
        var"##245" = var"##246" - var"##251"
        var"##254" = var"##245" ^ 2
        var"##256" = 4.0f0var"##251"
        var"##255" = var"##256" * var"##250"
        var"##253" = var"##254" + var"##255"
        var"##252" = sqrt(var"##253")
        var"##244" = var"##245" + var"##252"
        var"##243" = var"##244" * M
        var"##258" = 0.5f0var"##244"
        var"##257" = sqrt(var"##258")
        var"##242" = var"##243" * var"##257"
        var"##261" = var"##244" * var"##244"
        var"##260" = 0.25f0var"##261"
        var"##262" = var"##251" * var"##250"
        var"##259" = var"##260" + var"##262"
        var"##241" = var"##242" / var"##259"
        var"##240" = -1 - var"##241"
        var"##239" = var"##240" * v0
        var"##265" = -var"##241"
        var"##269" = var"##257" * x1
        var"##270" = a * x2
        var"##268" = var"##269" + var"##270"
        var"##267" = -var"##268"
        var"##271" = var"##258" + var"##251"
        var"##266" = var"##267" / var"##271"
        var"##264" = var"##265" * var"##266"
        var"##263" = var"##264" * v1
        var"##238" = var"##239" + var"##263"
        var"##277" = var"##257" * x2
        var"##278" = a * x1
        var"##276" = var"##277" - var"##278"
        var"##275" = -var"##276"
        var"##274" = var"##275" / var"##271"
        var"##273" = var"##265" * var"##274"
        var"##272" = var"##273" * v2
        var"##237" = var"##238" + var"##272"
        var"##282" = -(x3)
        var"##281" = var"##282" / var"##257"
        var"##280" = var"##265" * var"##281"
        var"##279" = var"##280" * v3
        var"##236" = var"##237" + var"##279"
        dx0 = var"##236"
        var"##286" = var"##264" * v0
        var"##290" = var"##241" * var"##266"
        var"##289" = var"##290" * var"##266"
        var"##288" = 1 - var"##289"
        var"##287" = var"##288" * v1
        var"##285" = var"##286" + var"##287"
        var"##293" = -var"##274"
        var"##292" = var"##293" * var"##290"
        var"##291" = var"##292" * v2
        var"##284" = var"##285" + var"##291"
        var"##296" = -var"##281"
        var"##295" = var"##296" * var"##290"
        var"##294" = var"##295" * v3
        var"##283" = var"##284" + var"##294"
        dx1 = var"##283"
        var"##300" = var"##273" * v0
        var"##301" = var"##292" * v1
        var"##299" = var"##300" + var"##301"
        var"##305" = var"##241" * var"##274"
        var"##304" = var"##305" * var"##274"
        var"##303" = 1 - var"##304"
        var"##302" = var"##303" * v2
        var"##298" = var"##299" + var"##302"
        var"##308" = -var"##305"
        var"##307" = var"##308" * var"##281"
        var"##306" = var"##307" * v3
        var"##297" = var"##298" + var"##306"
        dx2 = var"##297"
        var"##312" = var"##280" * v0
        var"##313" = var"##295" * v1
        var"##311" = var"##312" + var"##313"
        var"##314" = var"##307" * v2
        var"##310" = var"##311" + var"##314"
        var"##318" = var"##241" * var"##281"
        var"##317" = var"##318" * var"##281"
        var"##316" = 1 - var"##317"
        var"##315" = var"##316" * v3
        var"##309" = var"##310" + var"##315"
        dx3 = var"##309"
        dv0 = 0
        var"##328" = -var"##266"
        var"##327" = var"##328" * v1
        var"##326" = var"##327" * v1
        var"##331" = v1 * v2
        var"##332" = v2 * v1
        var"##330" = var"##331" + var"##332"
        var"##329" = var"##293" * var"##330"
        var"##325" = var"##326" + var"##329"
        var"##335" = v1 * v3
        var"##336" = v3 * v1
        var"##334" = var"##335" + var"##336"
        var"##333" = var"##296" * var"##334"
        var"##324" = var"##325" + var"##333"
        var"##342" = 1 / var"##259"
        var"##344" = var"##257" * M
        var"##348" = 2var"##257"
        var"##347" = 1 / var"##348"
        var"##346" = var"##243" * var"##347"
        var"##345" = 0.5f0var"##346"
        var"##343" = var"##344" + var"##345"
        var"##341" = var"##342" * var"##343"
        var"##352" = var"##241" / var"##259"
        var"##351" = -var"##352"
        var"##350" = var"##244" * var"##351"
        var"##349" = 0.5f0var"##350"
        var"##340" = var"##341" + var"##349"
        var"##353" = 2 * x1
        var"##339" = var"##340" * var"##353"
        var"##338" = var"##266" * var"##339"
        var"##358" = 1 / var"##271"
        var"##357" = -var"##358"
        var"##361" = x1 * var"##347"
        var"##360" = x1 * var"##361"
        var"##359" = var"##257" + var"##360"
        var"##356" = var"##357" * var"##359"
        var"##364" = var"##266" / var"##271"
        var"##363" = -var"##364"
        var"##362" = x1 * var"##363"
        var"##355" = var"##356" + var"##362"
        var"##354" = var"##241" * var"##355"
        var"##337" = var"##338" + var"##354"
        var"##323" = var"##324" * var"##337"
        var"##371" = -(v2)
        var"##370" = var"##371" * var"##274"
        var"##369" = v2 * var"##370"
        var"##375" = v2 * v3
        var"##376" = v3 * v2
        var"##374" = var"##375" + var"##376"
        var"##373" = var"##374" * var"##281"
        var"##372" = -var"##373"
        var"##368" = var"##369" + var"##372"
        var"##367" = var"##241" * var"##368"
        var"##379" = -var"##290"
        var"##378" = var"##379" * var"##330"
        var"##381" = var"##308" * v2
        var"##380" = var"##381" * v2
        var"##377" = var"##378" + var"##380"
        var"##366" = var"##367" + var"##377"
        var"##385" = -(a)
        var"##387" = x2 * var"##347"
        var"##386" = x1 * var"##387"
        var"##384" = var"##385" + var"##386"
        var"##383" = var"##357" * var"##384"
        var"##390" = var"##274" / var"##271"
        var"##389" = -var"##390"
        var"##388" = x1 * var"##389"
        var"##382" = var"##383" + var"##388"
        var"##365" = var"##366" * var"##382"
        var"##322" = var"##323" + var"##365"
        var"##398" = var"##357" * x2
        var"##397" = var"##398" * var"##347"
        var"##396" = var"##397" + var"##389"
        var"##395" = var"##396" * var"##366"
        var"##400" = 3var"##347"
        var"##404" = var"##281" / var"##257"
        var"##403" = -var"##404"
        var"##402" = 2var"##403"
        var"##408" = var"##379" * var"##334"
        var"##409" = var"##308" * var"##374"
        var"##407" = var"##408" + var"##409"
        var"##412" = -2var"##318"
        var"##411" = var"##412" * v3
        var"##410" = var"##411" * v3
        var"##406" = var"##407" + var"##410"
        var"##414" = v3 * v0
        var"##413" = var"##265" * var"##414"
        var"##405" = var"##406" + var"##413"
        var"##401" = var"##402" * var"##405"
        var"##399" = var"##400" * var"##401"
        var"##394" = var"##395" + var"##399"
        var"##393" = 2.0f0var"##394"
        var"##416" = 2var"##340"
        var"##421" = var"##274" * var"##368"
        var"##425" = var"##281" * var"##281"
        var"##424" = -var"##425"
        var"##423" = var"##424" * v3
        var"##422" = var"##423" * v3
        var"##420" = var"##421" + var"##422"
        var"##428" = 2var"##281"
        var"##427" = var"##428" * var"##414"
        var"##426" = -4var"##427"
        var"##419" = var"##420" + var"##426"
        var"##429" = var"##266" * var"##324"
        var"##418" = var"##419" + var"##429"
        var"##433" = v2 * v0
        var"##432" = var"##433" * var"##293"
        var"##436" = v1 * v0
        var"##435" = var"##436" * var"##328"
        var"##440" = v3 * var"##281"
        var"##439" = -var"##440"
        var"##443" = -(v0)
        var"##445" = v1 * var"##266"
        var"##444" = -var"##445"
        var"##442" = var"##443" + var"##444"
        var"##447" = v2 * var"##274"
        var"##446" = -var"##447"
        var"##441" = var"##442" + var"##446"
        var"##438" = var"##439" + var"##441"
        var"##437" = v0 * var"##438"
        var"##434" = var"##435" + var"##437"
        var"##431" = var"##432" + var"##434"
        var"##448" = var"##443" * v0
        var"##430" = var"##431" + var"##448"
        var"##417" = var"##418" + var"##430"
        var"##415" = var"##416" * var"##417"
        var"##392" = var"##393" + var"##415"
        var"##391" = var"##392" * var"##353"
        var"##321" = var"##322" + var"##391"
        var"##452" = var"##265" * var"##382"
        var"##454" = var"##293" * var"##340"
        var"##453" = var"##454" * var"##353"
        var"##451" = var"##452" + var"##453"
        var"##450" = var"##433" * var"##451"
        var"##459" = v1 * v1
        var"##458" = -var"##459"
        var"##457" = var"##458" * var"##290"
        var"##456" = var"##457" * var"##355"
        var"##462" = var"##265" * var"##355"
        var"##464" = var"##328" * var"##340"
        var"##463" = var"##464" * var"##353"
        var"##461" = var"##462" + var"##463"
        var"##460" = var"##436" * var"##461"
        var"##455" = var"##456" + var"##460"
        var"##449" = var"##450" + var"##455"
        var"##320" = var"##321" + var"##449"
        var"##319" = -0.5f0var"##320"
        dv1 = var"##319"
        var"##470" = 2 * x2
        var"##469" = var"##392" * var"##470"
        var"##475" = x2 * var"##387"
        var"##474" = var"##257" + var"##475"
        var"##473" = var"##357" * var"##474"
        var"##476" = var"##389" * x2
        var"##472" = var"##473" + var"##476"
        var"##471" = var"##366" * var"##472"
        var"##468" = var"##469" + var"##471"
        var"##480" = var"##340" * var"##470"
        var"##479" = var"##266" * var"##480"
        var"##485" = x2 * var"##361"
        var"##484" = a + var"##485"
        var"##483" = var"##357" * var"##484"
        var"##486" = var"##363" * x2
        var"##482" = var"##483" + var"##486"
        var"##481" = var"##241" * var"##482"
        var"##478" = var"##479" + var"##481"
        var"##477" = var"##324" * var"##478"
        var"##467" = var"##468" + var"##477"
        var"##490" = var"##265" * var"##472"
        var"##493" = -var"##340"
        var"##492" = var"##493" * var"##470"
        var"##491" = var"##274" * var"##492"
        var"##489" = var"##490" + var"##491"
        var"##488" = var"##433" * var"##489"
        var"##496" = var"##457" * var"##482"
        var"##499" = var"##265" * var"##482"
        var"##500" = var"##464" * var"##470"
        var"##498" = var"##499" + var"##500"
        var"##497" = var"##436" * var"##498"
        var"##495" = var"##496" + var"##497"
        var"##503" = v0 * v0
        var"##502" = -var"##503"
        var"##501" = var"##502" * var"##480"
        var"##494" = var"##495" + var"##501"
        var"##487" = var"##488" + var"##494"
        var"##466" = var"##467" + var"##487"
        var"##465" = -0.5f0var"##466"
        dv2 = var"##465"
        var"##510" = 1 / var"##257"
        var"##509" = -var"##510"
        var"##514" = 0.5f0var"##347"
        var"##518" = 2var"##252"
        var"##517" = 1 / var"##518"
        var"##516" = var"##517" * var"##256"
        var"##515" = var"##516" + 1
        var"##513" = var"##514" * var"##515"
        var"##519" = 2 * x3
        var"##512" = var"##513" * var"##519"
        var"##511" = var"##403" * var"##512"
        var"##508" = var"##509" + var"##511"
        var"##507" = var"##405" * var"##508"
        var"##526" = 0.5f0var"##396"
        var"##525" = var"##526" * var"##515"
        var"##524" = var"##265" * var"##525"
        var"##531" = var"##343" * var"##515"
        var"##530" = var"##342" * var"##531"
        var"##534" = var"##258" * var"##515"
        var"##533" = var"##251" + var"##534"
        var"##532" = var"##351" * var"##533"
        var"##529" = var"##530" + var"##532"
        var"##528" = -var"##529"
        var"##527" = var"##274" * var"##528"
        var"##523" = var"##524" + var"##527"
        var"##522" = var"##523" * var"##519"
        var"##521" = var"##433" * var"##522"
        var"##543" = var"##357" * x1
        var"##542" = var"##543" * var"##347"
        var"##541" = var"##542" + var"##363"
        var"##540" = var"##457" * var"##541"
        var"##539" = 0.5f0var"##540"
        var"##538" = var"##539" * var"##515"
        var"##547" = 0.5f0var"##265"
        var"##548" = var"##541" * var"##515"
        var"##546" = var"##547" * var"##548"
        var"##549" = var"##328" * var"##529"
        var"##545" = var"##546" + var"##549"
        var"##544" = var"##436" * var"##545"
        var"##537" = var"##538" + var"##544"
        var"##552" = v1 * var"##545"
        var"##553" = var"##443" * var"##529"
        var"##551" = var"##552" + var"##553"
        var"##550" = v0 * var"##551"
        var"##536" = var"##537" + var"##550"
        var"##535" = var"##536" * var"##519"
        var"##520" = var"##521" + var"##535"
        var"##506" = var"##507" + var"##520"
        var"##557" = var"##392" * var"##515"
        var"##558" = var"##417" * var"##529"
        var"##556" = var"##557" + var"##558"
        var"##561" = var"##266" * var"##529"
        var"##564" = 0.5f0var"##541"
        var"##563" = var"##564" * var"##515"
        var"##562" = var"##241" * var"##563"
        var"##560" = var"##561" + var"##562"
        var"##559" = var"##324" * var"##560"
        var"##555" = var"##556" + var"##559"
        var"##554" = var"##555" * var"##519"
        var"##505" = var"##506" + var"##554"
        var"##504" = -0.5f0var"##505"
        dv3 = var"##504"

    end
    
    return dx0, dx1, dx2, dx3, dv0, dv1, dv2, dv3

end

@inline function calculate_differential(state::NTuple{N, T}, metric::KerrMetric{T}) where {N,T}
    x0, x1, x2, x3, v0, v1, v2, v3 = state
    dstate = calculate_differential(x0, x1, x2, x3, v0, v1, v2, v3, metric)
    return dstate
end

@inline function yield_r2(x0::T, x1::T, x2::T, x3::T, metric::KerrMetric{T}) where T

    a = metric.a
    M = metric.M
    @fastmath begin
        x1_2 = x1*x1
        x2_2 = x2*x2
        x3_2 = x3*x3
        R2 = x1_2 + x2_2 + x3_2
        a2 = a*a
        sub1 = R2 - a2
        r2 = T(0.5) * (sub1 + sqrt(sub1^2 + T(4) * a2 * x3_2))
    end

    return r2

end

@inline function RK4step(x0::T, x1::T, x2::T, x3::T, v0::T, v1::T, v2::T, v3::T, 
                         metric::KerrMetric{T}, dt::T) where T

                        #for some reason, the original, tuble-base logic allocated here.
    @fastmath begin 
        dx0_1, dx1_1, dx2_1, dx3_1, dv0_1, dv1_1, dv2_1, dv3_1 = 
            calculate_differential(x0, x1, x2, x3, v0, v1, v2, v3, metric)
        dt_half = dt * T(0.5)
        dx0_2, dx1_2, dx2_2, dx3_2, dv0_2, dv1_2, dv2_2, dv3_2 = 
            calculate_differential(
                x0 + dt_half * dx0_1,
                x1 + dt_half * dx1_1,
                x2 + dt_half * dx2_1,
                x3 + dt_half * dx3_1,
                v0 + dt_half * dv0_1,
                v1 + dt_half * dv1_1,
                v2 + dt_half * dv2_1,
                v3 + dt_half * dv3_1,
                metric
            )

        dx0_3, dx1_3, dx2_3, dx3_3, dv0_3, dv1_3, dv2_3, dv3_3 = 
            calculate_differential(
                x0 + dt_half * dx0_2,
                x1 + dt_half * dx1_2,
                x2 + dt_half * dx2_2,
                x3 + dt_half * dx3_2,
                v0 + dt_half * dv0_2,
                v1 + dt_half * dv1_2,
                v2 + dt_half * dv2_2,
                v3 + dt_half * dv3_2,
                metric
            )

        dx0_4, dx1_4, dx2_4, dx3_4, dv0_4, dv1_4, dv2_4, dv3_4 = 
            calculate_differential(
                x0 + dt * dx0_3,
                x1 + dt * dx1_3,
                x2 + dt * dx2_3,
                x3 + dt * dx3_3,
                v0 + dt * dv0_3,
                v1 + dt * dv1_3,
                v2 + dt * dv2_3,
                v3 + dt * dv3_3,
                metric
            )
        
        renorm_6 = 1 / T(6)
        renorm_3 = 1 / T(3)
        dx0 = renorm_6 * (dx0_1 + dx0_4) + renorm_3 * (dx0_2 + dx0_3)
        dx1 = renorm_6 * (dx1_1 + dx1_4) + renorm_3 * (dx1_2 + dx1_3)
        dx2 = renorm_6 * (dx2_1 + dx2_4) + renorm_3 * (dx2_2 + dx2_3)
        dx3 = renorm_6 * (dx3_1 + dx3_4) + renorm_3 * (dx3_2 + dx3_3)
        dv0 = renorm_6 * (dv0_1 + dv0_4) + renorm_3 * (dv0_2 + dv0_3)
        dv1 = renorm_6 * (dv1_1 + dv1_4) + renorm_3 * (dv1_2 + dv1_3)
        dv2 = renorm_6 * (dv2_1 + dv2_4) + renorm_3 * (dv2_2 + dv2_3)
        dv3 = renorm_6 * (dv3_1 + dv3_4) + renorm_3 * (dv3_2 + dv3_3)
    end
    
    return (dx0, dx1, dx2, dx3, dv0, dv1, dv2, dv3)
end